apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadwfvl4625-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadwfvl4625-tenant-component
    app.kubernetes.io/part-of: loadwfvl4625-tenant-app
  name: loadwfvl4625-tenant-component
  namespace: loadwfvl4625-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadwfvl4625-tenant-component
    weight: null
status: {}
